// File generated by FlutterFire CLI.
// This is a TEMPLATE file - replace with actual firebase_options.dart after running:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example options below. Replace with your actual Firebase configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlXOhL32ytjS_0aOGrwh3zUPX1kf6A0FM',
    appId: '1:168654237897:web:8ea56bb268adbf3f7f5d18',
    messagingSenderId: '168654237897',
    projectId: 'laporin-b4a18',
    authDomain: 'laporin-b4a18.firebaseapp.com',
    storageBucket: 'laporin-b4a18.firebasestorage.app',
    measurementId: 'G-LWYJPRQLX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsSID1TnbC5Djrna__6g8zVQalZDsgpzE',
    appId: '1:168654237897:android:d448cae830ddb42e7f5d18',
    messagingSenderId: '168654237897',
    projectId: 'laporin-b4a18',
    storageBucket: 'laporin-b4a18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdsrOKlyKOEUVfAOK43chjJl404aU0Pg8',
    appId: '1:168654237897:ios:31df9240492bf2b47f5d18',
    messagingSenderId: '168654237897',
    projectId: 'laporin-b4a18',
    storageBucket: 'laporin-b4a18.firebasestorage.app',
    iosBundleId: 'com.example.laporin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdsrOKlyKOEUVfAOK43chjJl404aU0Pg8',
    appId: '1:168654237897:ios:31df9240492bf2b47f5d18',
    messagingSenderId: '168654237897',
    projectId: 'laporin-b4a18',
    storageBucket: 'laporin-b4a18.firebasestorage.app',
    iosBundleId: 'com.example.laporin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlXOhL32ytjS_0aOGrwh3zUPX1kf6A0FM',
    appId: '1:168654237897:web:7febe5f00f96acae7f5d18',
    messagingSenderId: '168654237897',
    projectId: 'laporin-b4a18',
    authDomain: 'laporin-b4a18.firebaseapp.com',
    storageBucket: 'laporin-b4a18.firebasestorage.app',
    measurementId: 'G-LY782K91QC',
  );

}